server:
  port: 8280

spring:
  application:
    name: borrowservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'





